"""email_token table

Revision ID: cfc34d448b47
Revises: a730f0e9380e
Create Date: 2025-05-30 22:20:02.538075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc34d448b47'
down_revision: Union[str, None] = 'a730f0e9380e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('exp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_token_exp'), ['exp'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_token_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_token_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_token_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_token_type'))
        batch_op.drop_index(batch_op.f('ix_email_token_jti'))
        batch_op.drop_index(batch_op.f('ix_email_token_exp'))

    op.drop_table('email_token')
    # ### end Alembic commands ###
